NavigaMagazin/NavigaMagazin/Models/Entity/videoTable.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavigaMagazin.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class videoTable
    {
        public long id { get; set; }
        public string videotitle { get; set; }
        public string videodescription { get; set; }
        public string videolink { get; set; }
        public string url { get; set; }
        public Nullable<System.DateTime> releasetime { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public Nullable<int> isaktif { get; set; }
        public string showroom { get; set; }
    }
}

NavigaMagazin/NavigaMagazin/Controllers/AdminPartialController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NavigaMagazin.Models.Entity
{
    public class AdminPartialController : Controllers.BaseController
    {
        // GET: AdminPartial
        navigaEntities db = new navigaEntities();
        [HttpGet]
        public ActionResult UserAdd()
        {
            List<SelectListItem> UserRoleList = (from i in db.UserRoleTables.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = i.rolename,
                                                 Value = i.id.ToString()

                                             }).ToList();
            ViewBag.roles = UserRoleList;
            return PartialView();
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult UserAdd(string username, string usersurname, string userpassword, string useremail, string userphoto, int userroleid, string userfacebook, string userlinkedin, string usertwitter, string useryoutube)
        {
            var add = new UserTable
            {
                username = username,
                usersurname = usersurname,
                userpassword = userpassword,
                useremail = useremail,
                userroleid = userroleid,
                userfacebook = userfacebook,
                userlinkedin = userlinkedin,
                usertwitter = usertwitter,
                useryoutube = useryoutube,
                isaktif = 1,
                creationtime = DateTime.Now,
                updatetime = DateTime.Now,
            };

            if (userphoto != null)
            {
                var userphotofile = Request.Files[0];
                var fileInfo = new FileInfo(userphotofile.FileName);
                var pic = "User_Profil_" + DateTime.Now.Ticks + fileInfo.Extension;
                var filePath = "/Photos/UserPhotos/" + pic;
                var tempFilePath = Server.MapPath("~\\Photos\\UserPhotos\\" + pic);
                userphotofile.SaveAs(tempFilePath);
                add.userphoto = filePath;
            }

            var addlog = new ManualLog
            {
                logexp = "Yeni Kullanıcı Eklendi, Eklenen kullanıcı :"+username+" "+usersurname,
                whodidit = "Sessionİsmi",
                processingtime = DateTime.Now,
            };
            db.ManualLogs.Add(addlog);
            db.UserTables.Add(add);
            db.SaveChanges();
            return Redirect(ControllerContext.HttpContext.Request.UrlReferrer.ToString());
        }
        [HttpGet]
        public ActionResult CategoryAdd()
        {
            List<SelectListItem> MenuList = (from i in db.MenuTables.ToList()
                                                 select new SelectListItem
                                                 {
                                                     Text = i.menuname,
                                                     Value = i.id.ToString()

                                                 }).ToList();
            ViewBag.menus = MenuList;
            return PartialView();
        }
        [HttpPost]
        public ActionResult CategoryAdd(string categoryname, int menuid)
        {
            var add = new CategoryTable
            {
                categoryname = categoryname,
                menuid = menuid,
            };
            var addlog = new ManualLog
            {
                logexp = "Yeni Kategori Eklendi, Eklenen Kategori :" + categoryname,
                whodidit = "Sessionİsmi",
                processingtime = DateTime.Now,
            };
            db.ManualLogs.Add(addlog);
            db.CategoryTables.Add(add);
            db.SaveChanges();
            return Redirect(ControllerContext.HttpContext.Request.UrlReferrer.ToString());
        }
        public ActionResult Categories()
        {
            var catlist = (from s in db.CategoryTables select s).ToList();
            return PartialView(catlist);
        }
        public ActionResult CategoryDelete(int id)
        {
            var cat = db.CategoryTables.Find(id);
            var addlog = new ManualLog
            {
                logexp = "Kategori Silindi, Silinen Kategori : " + cat.categoryname ,
                whodidit = "Sessionİsmi",
                processingtime = DateTime.Now,
            };
            db.ManualLogs.Add(addlog);
            db.CategoryTables.Remove(cat);
            db.SaveChanges();
            return Redirect(ControllerContext.HttpContext.Request.UrlReferrer.ToString());

        }
        public ActionResult VideoAdd()
        {
            
            return PartialView();
        }
        [HttpPost]
        public ActionResult VideoAdd(string videotitle, string videodescription, string releasetime, string videolink, string showroom)
        {
            string rtime = releasetime;
            //DateTime rtime = DateTime.ParseExact(releasetime, "yyyy/MM/dd", null);
            var add = new videoTable
            {
                videotitle = videotitle,
                videodescription = videodescription,
                isaktif = 1,
                videolink = videolink,
                createtime = DateTime.Now,
                updatetime = DateTime.Now,
                releasetime = Convert.ToDateTime(rtime),
                showroom = showroom,
            };
            var addlog = new ManualLog
            {
                logexp = "Yeni Video Eklendi, Eklenen Video :" + videotitle,
                whodidit = "Sessionİsmi",
                processingtime = DateTime.Now,
            };
            db.ManualLogs.Add(addlog);
            db.videoTables.Add(add);
            db.SaveChanges();
            return Redirect(ControllerContext.HttpContext.Request.UrlReferrer.ToString());
        }
        public ActionResult AdAdd()
        {
            return PartialView();
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult AdAdd(string advertisingname, string advertisinglink, string advertisingphoto, string advertisingformat, string advertisingstart, string advertisingend, string fixedad)
        {
            string stime = advertisingstart;
            string etime = advertisingend;
            var add = new AdvertisingTable
            {
                advertisingname = advertisingname,
                advertisinglink = advertisinglink,
                fixedad = fixedad,
                createtime = DateTime.Now,
                updatetime = DateTime.Now,
                numberofclicks = 1,
                isaktif = 1,
                numberofview = 1,
                advertisingstart = Convert.ToDateTime(stime),
                advertisingend = Convert.ToDateTime(etime),
            };
            if(advertisingformat == "260x230")
            {
               
                var control = (from s in db.AdvertisingTables
                               where s.advertising260x230 == "true" &&
                               s.advertisingstart < DateTime.Now && s.advertisingend > DateTime.Now
                               && s.fixedad != "true"
                               select s).Count();
                if(control >= 2 && fixedad != "true")
                {
                    TempData["ads"] = string.Format("no");
                    return RedirectToAction("Index", "Advertisement");
                }
                else
                {
                    add.advertising260x230 = "true";
                }
                
            }
            else if(advertisingformat == "320x270")
            {
                var control1 = (from s in db.AdvertisingTables
                               where s.advertising320x270 == "true" &&
                               s.advertisingstart < DateTime.Now && s.advertisingend > DateTime.Now
                               && s.fixedad != "true"
                               select s).Count();
                if (control1 >= 2 && fixedad != "true")
                {
                    TempData["ads"] = string.Format("no");
                    return RedirectToAction("Index", "Advertisement");
                }
                else
                {
                    add.advertising320x270 = "true";
                }
                
            }
            else if(advertisingformat == "728x90")
            {
                var control2 = (from s in db.AdvertisingTables
                                where s.advertising728x90 == "true" &&
                                s.advertisingstart < DateTime.Now && s.advertisingend > DateTime.Now
                                && s.fixedad != "true"
                                select s).Count();
                if (control2 >= 2 && fixedad != "true")
                {
                    TempData["ads"] = string.Format("no");
                    return RedirectToAction("Index", "Advertisement");
                }
                else
                {
                    add.advertising728x90 = "true";
                }
            }
            else if (advertisingformat == "728x90banner")
            {
                var control2 = (from s in db.AdvertisingTables
                                where s.advertising728x90banner == "true" &&
                                s.advertisingstart < DateTime.Now && s.advertisingend > DateTime.Now
                                && s.fixedad != "true"
                                select s).Count();
                if (control2 >= 2 && fixedad != "true")
                {
                    TempData["ads"] = string.Format("no");
                    return RedirectToAction("Index", "Advertisement");
                }
                else
                {
                    add.advertising728x90banner = "true";
                }
            }

NavigaMagazin/NavigaMagazin/Controllers/VideoController.cs
using NavigaMagazin.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NavigaMagazin.Controllers
{
    public class VideoController : BaseController
    {
        // GET: Video
        navigaEntities db = new navigaEntities();
        public ActionResult Index()
        {
            var videos = (from s in db.videoTables
                         orderby s.releasetime descending
                         select s).ToList();
            return View(videos);
        }

        public ActionResult VideoDelete(int id)
        {
            UserTable currentUser = (UserTable)Session["MySessionUser"];
            var video = db.videoTables.Find(id);
            var addlog = new ManualLog
            {
                logexp = "Video Silindi, Silinen Video : " + video.videotitle,
                whodidit = currentUser.username + " " + currentUser.usersurname,
                processingtime = DateTime.Now,
            };
            db.ManualLogs.Add(addlog);
            db.videoTables.Remove(video);
            db.SaveChanges();
            return Redirect(ControllerContext.HttpContext.Request.UrlReferrer.ToString());
        }
        [HttpGet]
        public ActionResult VideoUpdate(int id)
        {
            var video = db.videoTables.Find(id);
            return View("VideoUpdate", video);
        }
        [HttpPost]
        public ActionResult VideoUpdate(videoTable p1)
        {
            UserTable currentUser = (UserTable)Session["MySessionUser"];
            var video = db.videoTables.Find(p1.id);
            var zaman = p1.releasetime;
            video.videotitle = p1.videotitle;
            video.videodescription = p1.videodescription;
            video.videolink = p1.videolink;
            video.showroom = p1.showroom;
            video.updatetime = DateTime.Now;
            video.releasetime = Convert.ToDateTime(zaman);

            var addlog = new ManualLog
            {
                logexp = "Video Güncellendi, Güncellenen Video : " + video.videotitle,
                whodidit = currentUser.username + " " + currentUser.usersurname,
                processingtime = DateTime.Now,
            };
            db.ManualLogs.Add(addlog);

            db.SaveChanges();
            return RedirectToAction("Index");

        }

        public ActionResult SearchVideo(string searchkey)
        {
            var search = from x in db.videoTables
                         select x;
            if (!String.IsNullOrEmpty(searchkey))
            {
                search = search.Where(s => s.videotitle.Contains(searchkey)
                || s.videodescription.Contains(searchkey)
                );
            }
            ViewBag.Words = searchkey;
            return View(search.ToList());
        }
    }
}

NavigaMagazin/NavigaMagazin/Views/Video/Index.cshtml
@using NavigaMagazin.Models.Entity

@{
    ViewBag.Title = "Video Yönetimi";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<script>
    $('#myModal').on('shown.bs.modal', function () {
        $('#myInput').trigger('focus')
    })
    $('#myModal2').on('shown.bs.modal', function () {
        $('#myInput2').trigger('focus')
    })
    $('#myModal3').on('shown.bs.modal', function () {
        $('#myInput3').trigger('focus')
    })
    $('#myModal4').on('shown.bs.modal', function () {
        $('#myInput4').trigger('focus')
    })
</script>
<div class="page-header row no-gutters py-4">
    <div class="col-6 col-sm-6 text-center text-sm-left mb-0">
        <span class="text-uppercase page-subtitle">Video Yönetimi</span>
    </div>


    <div class="col-6 col-sm-6 text-center mb-0 ">
        <button class="btn btn-primary pull-right" data-toggle="modal" data-target="#exampleModal">Video Ara</button>
        <button class="btn btn-primary pull-right" data-toggle="modal" data-target="#exampleModal2">Yeni Video</button>

    </div>
</div>
<hr />
<div class="row">

    @foreach (var videos in Model)
    {
    <div class="col-lg-4 border">
        <iframe src="@videos.videolink" style="width:100%!important; height:auto;"></iframe>
        <h5>@videos.videotitle </h5><br />
        <div class="row">
            <div class="col-lg-12 text-right">
                <a href="@Url.Action("VideoUpdate", "Video" , new { id = videos.id })"><i class="fas fa-pencil-alt"></i></a>
                <a href="@Url.Action("VideoDelete", "Video" , new { id = videos.id })" onclick="return confirm('@videos.videotitle adlı Silmek İstediğinize Emin Misiniz?')"><i class="fas fa-trash"></i></a>
            </div>
        </div>
    </div>
        
        
        @*<div class="col-lg-3 col-md-6 col-sm-12 mb-4">
                <div class="card card-small card-post card-post--1">
                    <div class="card-post__image" style="background-image: url('@posts.postphoto');">
                        <a href="@Url.Action("DeleteContent", "Contentdetail" , new { id = posts.id })" onclick="return confirm('Bu İçeriği Silmek İstediğinize Emin Misiniz?')"><i class="material-icons badge badge-pill badge-secondary" style="color:white; padding:10px;">X</i></a>
                        <p class="card-post__category badge badge-pill badge-dark">@posts.CategoryTable.categoryname </p>
                        <div class="card-post__author d-flex">
                            <a href="#" class="card-post__author-avatar card-post__author-avatar--small" style="background-image: url('@posts.UserTable.userphoto')"></a>
                        </div>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">
                            <a class="text-fiord-blue" href="@Url.Action("UpdateContent", "Contentdetail" , new { id = posts.id })">@posts.posttitle</a>
                        </h5>
                        <span class="text-muted">@posts.releasetime.ToString("dd.MM.yyyy")</span>
                    </div>
                </div>
            </div>*@
    }

    
</div>
@*İçerik Ara*@
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form action="@Url.Action("SearchVideo", "Video")" method="post" enctype="multipart/form-data" class="form-group">
                <div class="modal-header">
                    <h5 class="modal-title text-center" id="exampleModalLabel">Video Ara</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <input type="text" name="searchkey" placeholder="Video Ara" required class="form-control" /><br />

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Kapat</button>
                    <input type="submit" class="btn btn-primary" value="Ara" />
                </div>
            </form>

        </div>
    </div>
</div>
@*Yeni Kategori*@
<div class="modal fade" id="exampleModal2" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">

            @{Html.RenderAction("VideoAdd", "AdminPartial");}
        </div>
    </div>
</div>

NavigaMagazin/NavigaMagazin/Views/Video/SearchVideo.cshtml
@using NavigaMagazin.Models.Entity
@{
    ViewBag.Title = "SearchVideo";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<script>
    $('#myModal').on('shown.bs.modal', function () {
        $('#myInput').trigger('focus')
    })
    $('#myModal2').on('shown.bs.modal', function () {
        $('#myInput2').trigger('focus')
    })
    $('#myModal3').on('shown.bs.modal', function () {
        $('#myInput3').trigger('focus')
    })
    $('#myModal4').on('shown.bs.modal', function () {
        $('#myInput4').trigger('focus')
    })
</script>
<div class="page-header row no-gutters py-4">
    <div class="col-6 col-sm-6 text-center text-sm-left mb-0">
        <span class="text-uppercase page-subtitle">Aranan Video : @ViewBag.Words</span>
    </div>


    <div class="col-6 col-sm-6 text-center mb-0 ">
        <button class="btn btn-primary pull-right" data-toggle="modal" data-target="#exampleModal">Video Ara</button>
        

    </div>
</div>
<hr />
<div class="row">

    @foreach (var videos in Model)
    {
        <div class="col-lg-4 border">
            <iframe src="@videos.videolink" style="width:100%!important; height:auto;"></iframe>
            <h5>@videos.videotitle </h5><br />
            <div class="row">
                <div class="col-lg-12 text-right">
                    <a href="@Url.Action("VideoUpdate", "Video" , new { id = videos.id })"><i class="fas fa-pencil-alt"></i></a>
                    <a href="@Url.Action("VideoDelete", "Video" , new { id = videos.id })" onclick="return confirm('@videos.videotitle adlı Silmek İstediğinize Emin Misiniz?')"><i class="fas fa-trash"></i></a>
                </div>
            </div>
        </div>

    }


</div>
@*İçerik Ara*@
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form action="@Url.Action("SearchVideo", "Video")" method="post" enctype="multipart/form-data" class="form-group">
                <div class="modal-header">
                    <h5 class="modal-title text-center" id="exampleModalLabel">Video Ara</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <input type="text" name="searchkey" placeholder="Video Ara" required class="form-control" /><br />

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Kapat</button>
                    <input type="submit" class="btn btn-primary" value="Ara" />
                </div>
            </form>

        </div>
    </div>
</div>
@*Yeni Kategori*@
@*<div class="modal fade" id="exampleModal2" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">

            @{Html.RenderAction("VideoAdd", "AdminPartial");}
        </div>
    </div>
</div>*@

NavigaMagazin/NavigaMagazin/Views/Video/VideoUpdate.cshtml
@model NavigaMagazin.Models.Entity.videoTable
@{
    ViewBag.Title = "VideoUpdate";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<div class="page-header row no-gutters py-4">
    <div class="col-12 col-sm-12 text-center text-sm-left mb-0">
        <span class="text-uppercase page-subtitle">Video Güncelleme</span>
    </div>
</div>
<hr />
@using (Html.BeginForm("VideoUpdate", "Video", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="main-content-container container-fluid px-12">
        <div class="row">
            <div class="col-lg-12 col-md-12">
                <div class="card card-small mb-9">
                    <div class="card-body">
                        <label>Video</label>
                        <iframe src="@Model.videolink" style="width:100%!important; height:auto;"></iframe>
                        <label>Video Adı</label>
                        @Html.TextBoxFor(m => m.videotitle, new { @class = "form-control form-control-lg mb-3" })
                        <label>video Açıklaması</label>
                        @Html.TextAreaFor(m => m.videodescription, new { @class = "form-control form-control-lg mb-3" })
                        <label>Video Linki</label>
                        @Html.TextBoxFor(m => m.videolink, new { @class = "form-control form-control-lg mb-3" })
                        <label>Yayınlanma Zamanı</label>
                        <input type="text" id="datepicker" name="releasetime" required="required" class="ml-auto" value="@Model.releasetime"><br />
                        
                        <label>Vitrin</label>
                        @if (Model.showroom == "true")
                        {
                            <input type="checkbox" name="showroom" value="true" checked />
                        }
                        else
                        {
                            <input type="checkbox" name="showroom" value="true" />
                        }
                        <br /><br />
                        <button class="btn btn-sm btn-accent ml-auto">
                            <i class="material-icons">file_copy</i> Kaydet
                        </button>
                    </div>
                </div>
            </div>

        </div>
    </div>

}

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.0/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js"></script>
<script>
    $(function () {


        $("#datepicker").datepicker({
            dateFormat: 'yy-mm-dd'
        }).datepicker();
        ;
    });
</script>