NavigaMagazin/NavigaMagazin/Controllers/ContentdetailController.cs
using NavigaMagazin.Models.Entity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NavigaMagazin.Helpers;
using PagedList;

namespace NavigaMagazin.Controllers
{
    public class ContentdetailController : BaseController
    {
        // GET: Content
        navigaEntities db = new navigaEntities();
        public ActionResult Index(int page = 1)
        {
            var posts = (from s in db.ContentTables
                         orderby s.releasetime descending where s.approved == "true"
                         select s).ToList().ToPagedList(page, 20);         
            return View(posts);
        }
        [HttpGet]
        public ActionResult ContentAdd()
        {
            List<SelectListItem> userlist = (from i in db.UserTables.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = i.username + i.usersurname,
                                                 Value = i.id.ToString()

                                             }).ToList();
            List<SelectListItem> categorylist = (from i in db.CategoryTables.ToList()
                                                 select new SelectListItem
                                                 {
                                                     Text = i.categoryname +" - " + i.MenuTable.menuname,
                                                     Value = i.id.ToString()

                                                 }).ToList();
            ViewBag.users = userlist;
            ViewBag.categories = categorylist;
            return View();
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ContentAdd(string posttitle, string postspottext, string postcontent, int userid, int categoryid, string postphoto, string releasetime, int isaktif, string postshowroom) {
            string rtime = releasetime;
            var seourl = string.IsNullOrEmpty(posttitle.Trim()) ? Utility.UrlSeo(posttitle.Trim()) : Utility.UrlSeo(posttitle.Trim());
            UserTable currentUser = (UserTable)Session["MySessionUser"];
            var add = new ContentTable
            {
                categoryid = categoryid,
                userid = userid,
                posttitle = posttitle,
                postspottext = postspottext,
                postcontent = postcontent,
                isaktif = isaktif,
                releasetime = Convert.ToDateTime(rtime),
                postdislike = 0,
                postlike = 0,
                postview = 0,
                createtime = DateTime.Now,
                updatetime = DateTime.Now,
                postshowroom = postshowroom,
                url = seourl,
                approved = "true",
            };
            if (postphoto != null)
            {
                var image = Request.Files[0];
                if ((5 * 1024 * 1024) < image.ContentLength) //5MB
                    throw new Exception("hata mesaaji");
                var fileInfo = new FileInfo(image.FileName);
                var pic = "ContentPic_" + DateTime.Now.Ticks + fileInfo.Extension;
                var filePath = "/Photos/ContentPhotos/" + pic;
                var tempFilePath = Server.MapPath("~\\Photos\\ContentPhotos\\" + pic);
                image.SaveAs(tempFilePath);
                add.postphoto = filePath;
            }
            var addlog = new ManualLog
            {
                logexp = "Yeni İçerik Eklendi , Eklenen İçerik : " + posttitle,
                whodidit = currentUser.username + " " + currentUser.usersurname,
                processingtime = DateTime.Now,
            };
            db.ManualLogs.Add(addlog);
            db.ContentTables.Add(add);
            db.SaveChanges();

            return RedirectToAction("/Index");
        }
        public ActionResult DeleteContent(int id)
        {
            //var comments = db.comenttables.Where(c => c.postid == id);
            //db.comenttables.RemoveRange(comments);
            UserTable currentUser = (UserTable)Session["MySessionUser"];
            var contentdelete = db.ContentTables.Find(id);
            var addlog = new ManualLog
            {
                logexp = "İçerik Silindi, Silinen İçerik : " + contentdelete.posttitle,
                whodidit = currentUser.username + " " + currentUser.usersurname,
                processingtime = DateTime.Now,
            };
            db.ManualLogs.Add(addlog);
            db.ContentTables.Remove(contentdelete);
            db.SaveChanges();
            return Redirect(ControllerContext.HttpContext.Request.UrlReferrer.ToString());
        }
        [HttpGet]
        public ActionResult UpdateContent(int id)
        {
            List<SelectListItem> userlist = (from i in db.UserTables.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = i.username + i.usersurname,
                                                 Value = i.id.ToString()
                                             }).ToList();
            List<SelectListItem> categorylist = (from i in db.CategoryTables.ToList()
                                                 select new SelectListItem
                                                 {
                                                     Text = i.categoryname + " - " + i.MenuTable.menuname,
                                                     Value = i.id.ToString()
                                                 }).ToList();
            ViewBag.users = userlist;
            ViewBag.categories = categorylist;
            var post = db.ContentTables.Find(id);
            return View("UpdateContent", post);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult UpdateContent(ContentTable p1)
        {
            UserTable currentUser = (UserTable)Session["MySessionUser"];
            var post = db.ContentTables.Find(p1.id);
            var zaman = p1.releasetime;
            var url = string.IsNullOrEmpty(p1.posttitle.Trim()) ? Utility.UrlSeo(p1.posttitle.Trim()) : Utility.UrlSeo(p1.posttitle.Trim());
            if(p1.postphoto != null)
            {
                var image = Request.Files[0];
                if ((5 * 1024 * 1024) < image.ContentLength) //5MB
                    throw new Exception("hata mesaaji");
                var fileInfo = new FileInfo(image.FileName);
                var pic = "ContentPic_" + DateTime.Now.Ticks + fileInfo.Extension;
                var filePath = "/Photos/ContentPhotos/" + pic;
                var tempFilePath = Server.MapPath("~\\Photos\\ContentPhotos\\" + pic);
                image.SaveAs(tempFilePath);
                post.postphoto = filePath;
            }
            post.postshowroom = p1.postshowroom;
            post.isaktif = p1.isaktif;
            post.categoryid = p1.categoryid;
            post.userid = p1.userid;
            post.posttitle = p1.posttitle;
            post.postspottext = p1.postspottext;
            post.postcontent = p1.postcontent;
            post.releasetime = Convert.ToDateTime(zaman);
            post.updatetime = DateTime.Now;
            post.url = url;
            var addlog = new ManualLog
            {
                logexp = "İçerik Güncellendi , Güncellenen İçerik : " + p1.posttitle,
                whodidit = currentUser.username + " " + currentUser.usersurname,
                processingtime = DateTime.Now,
            };
            db.ManualLogs.Add(addlog);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult SearchContent(string searchkey)
        {
            var search = from x in db.ContentTables
                         select x;
            if (!String.IsNullOrEmpty(searchkey))
            {
                search = search.Where(s => s.posttitle.Contains(searchkey)
                || s.postcontent.Contains(searchkey)
                );
            }
            ViewBag.Words = searchkey;
            return View(search.ToList());
        }
        [HttpGet]
        public ActionResult UpdateCat(int id)
        {
            List<SelectListItem> MenuList = (from i in db.MenuTables.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = i.menuname,
                                                 Value = i.id.ToString()

                                             }).ToList();
            ViewBag.menus = MenuList;
            var categorie = db.CategoryTables.Find(id);
            return View("UpdateCat", categorie);
        }
        [HttpPost]
        public ActionResult UpdateCat(CategoryTable p1)
        {
            UserTable currentUser = (UserTable)Session["MySessionUser"];
            var cat = db.CategoryTables.Find(p1.id);
            cat.categoryname = p1.categoryname;
            cat.menuid = p1.menuid;
            var addlog = new ManualLog
            {
                logexp = "Kategori Güncellendi , Güncellenene Kategori : " + p1.categoryname,
                whodidit = currentUser.username + " " + currentUser.usersurname,
                processingtime = DateTime.Now,
            };
            db.ManualLogs.Add(addlog);
            db.SaveChanges();

            return RedirectToAction("/Index");
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult AddUpload(string uploadname, string uploadurl)
        {
            var add = new UploadTable
            {
                uploadname = uploadname,
            };

            if (uploadurl != null)
            {
                var image = Request.Files[0];

NavigaMagazin/NavigaMagazin/Views/Contentdetail/ApprovalRequest.cshtml
@using NavigaMagazin.Models.Entity
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<ContentTable>
@{
    ViewBag.Title = "ApprovalRequest";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}


<div class="page-header row no-gutters py-4">
    <div class="col-12 col-sm-12 text-center text-sm-left mb-0">
        <span class="text-uppercase page-subtitle">Onaylanacak Gönderiler</span>
    </div>


   
</div>
<hr />
<div class="row">
    @{int i = 1;}
    @foreach (var posts in Model)
    {
        <div class="col-lg-3 col-md-6 col-sm-12 mb-4">
            <div class="card card-small card-post card-post--1">
                <div class="card-post__image" style="background-image: url('@posts.postphoto');">
                    <a href="@Url.Action("DeleteContent", "Contentdetail" , new { id = posts.id })" onclick="return confirm('Bu İçeriği Silmek İstediğinize Emin Misiniz?')"><i class="material-icons badge badge-pill badge-secondary" style="color:white; padding:10px;">X</i></a>
                    <p class="card-post__category badge badge-pill badge-dark">@posts.CategoryTable.categoryname </p>
                    <div class="card-post__author d-flex">
                        <a href="#" class="card-post__author-avatar card-post__author-avatar--small" style="background-image: url('@posts.UserTable.userphoto')"></a>
                    </div>
                </div>
                <div class="card-body">
                    <h5 class="card-title">
                        <a class="text-fiord-blue" href="@Url.Action("ToBeApproved", "Contentdetail" , new { id = posts.id })">@posts.posttitle</a>
                    </h5>
                    <span class="text-muted">@posts.createtime.Value.ToString("dd.MM.yyyy")</span>
                </div>
            </div>
        </div>
    }


</div>

<div class="row">

    <div class="col-lg-12 text-center">
        @Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { page }))
    </div>
</div>

NavigaMagazin/NavigaMagazin/Views/Contentdetail/ContentAdd.cshtml
@model NavigaMagazin.Models.Entity.ContentTable
@{
    ViewBag.Title = "ContentAdd";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<script>
    $('#myModal').on('shown.bs.modal', function () {
        $('#myInput').trigger('focus')
    })
    $('#myModal2').on('shown.bs.modal', function () {
        $('#myInput2').trigger('focus')
    })
    $('#myModal3').on('shown.bs.modal', function () {
        $('#myInput3').trigger('focus')
    })
    $('#myModal4').on('shown.bs.modal', function () {
        $('#myInput4').trigger('focus')
    })
</script>
<style>
    .modal-lg {
        width: 100% !important;
        max-width: 900px;
    }
</style>
<div class="page-header row no-gutters py-4">
    <div class="col-6 col-sm-6 text-center text-sm-left mb-0">
        <span class="text-uppercase page-subtitle">Yeni İçerik Ekle</span>
    </div>


    <div class="col-6 col-sm-6 text-center mb-0 ">
        <button class="btn btn-primary pull-right" data-toggle="modal" data-target="#exampleModal">Fotoğraf Yükle</button>
        <button class="btn btn-primary pull-right" data-toggle="modal" data-target="#exampleModal2">Yüklü Fotoğraflar</button>


    </div>
</div>
<hr />
<script src="https://cdn.ckeditor.com/4.15.1/full/ckeditor.js"></script>
<div class="main-content-container container-fluid px-4">


    <div class="row">
        <div class="col-lg-9 col-md-12">
            <div class="card card-small mb-3">
                <div class="card-body">
                    <form class="add-new-post" method="post" enctype="multipart/form-data">
                        <input class="form-control form-control-lg mb-3" type="text" placeholder="İçerik Başlığı - Max 65 Karakter" name="posttitle" required maxlength="65">
                        <input class="form-control form-control-lg mb-3" type="text" placeholder="Ön Görünüm Yazısı Max 170 karakter" name="postspottext" required maxlength="170">
                        <div class="add-new-post__editor mb-1">

                            <textarea name="postcontent"></textarea><br /><br />
                            <script>
                                CKEDITOR.replace('postcontent');
                            </script>
                        </div>

                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-12">
            <div class='card card-small mb-3'>
                <div class="card-header border-bottom">
                    <h6 class="m-0">Detaylar ve Fotoğraf</h6>
                </div>
                <div class='card-body p-0'>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item p-3">



                            <span class="d-flex mb-2">
                                <i class="material-icons mr-1">border_color</i>
                                <strong class="mr-1">Yazar </strong>


                                @Html.DropDownListFor(m => m.userid, (List<SelectListItem>)ViewBag.users, new { @class = "ml-auto" })
                            </span>

                            <span class="d-flex mb-2">
                                <i class="material-icons mr-1">flag</i>
                                <strong class="mr-1">Durum </strong>
                                <select class="ml-auto" name="isaktif">
                                    <option value="1">Aktif</option>
                                    <option value="2">Pasif</option>
                                </select>
                            </span>
                            <span class="d-flex mb-2">
                                <input type="checkbox" value="true" name="postshowroom"/>
                                <strong class="mr-1" style="margin-left:5px;"> Vitrinde Göster </strong>
                                 
                            </span>
                            <span class="d-flex mb-2">
                                <div class="row">
                                    <div class="col-lg-6">
                                        <strong class="mr-1">İçerik Fotoğrafı<br /> ( 695 x 460 ) </strong>
                                    </div>
                                    <div class="col-lg-6">
                                        <strong class="ml-1">
                                            <input type="file" name="postphoto" required />
                                        </strong>
                                    </div>
                                </div>
                            </span>
                        </li>
                    </ul>
                </div>
            </div>
            <div class='card card-small mb-3'>
                <div class="card-header border-bottom">
                    <h6 class="m-0">Kategori</h6>
                </div>
                <div class='card-body p-0'>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item p-3">
                            <span class="d-flex mb-2">
                                <i class="material-icons mr-1">storage</i>
                                <strong class="mr-1">Kategori </strong>
                                @Html.DropDownListFor(m => m.categoryid, (List<SelectListItem>)ViewBag.categories, new { @class = "ml-auto" })
                            </span>
                        </li>
                    </ul>
                </div>
            </div>
            <div class='card card-small mb-3'>
                <div class="card-header border-bottom">
                    <h6 class="m-0">Tarih</h6>
                </div>
                <div class='card-body p-0'>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item p-3">


                            <span class="d-flex mb-2">
                                <i class="material-icons mr-1">calendar_today</i>
                                <strong class="mr-1">Yayınlanma Zamanı </strong>
                                <input type="text" id="datepicker" name="releasetime" required="required" class="ml-auto"><br />
                            </span>

                        </li>
                        <li class="list-group-item d-flex px-3">

                            <button class="btn btn-sm btn-accent ml-auto">
                                <i class="material-icons">file_copy</i> Yayınla
                            </button>
                        </li>
                    </ul>
                </div>
            </div>
            </form>
        </div>
    </div>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.0/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js"></script>
    
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form action="@Url.Action("AddUpload", "Contentdetail")" method="post" enctype="multipart/form-data" class="form-group">
                <div class="modal-header">
                    <h5 class="modal-title text-center" id="exampleModalLabel">Fotoğraf Yükle</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <input type="text" name="uploadname" placeholder="Fotoğraf Adı" required class="form-control" /><br />
                    <input type="file" name="uploadurl" required/>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Kapat</button>
                    <input type="submit" class="btn btn-primary" value="Yükle" />
                </div>
            </form>

        </div>
    </div>
</div>
@*Yeni Kategori*@
<div class="modal fade" id="exampleModal2" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">

            @{Html.RenderAction("Uploaded", "AdminPartial");}
        </div>
    </div>
</div>

<script>
    function copyURI(evt) {
        evt.preventDefault();
        navigator.clipboard.writeText(evt.target.getAttribute('href')).then(() => {
            alert("Fotoğraf Linki Kopyalandı !");
        }, () => {
            /* clipboard write failed */
        });
    }

    $(function () {
        var dateNow = new Date();

        $("#datepicker").datepicker({
            dateFormat: "yy-mm-dd",
        }).datepicker('setDate', new Date());
        ;
    });

    
</script>

NavigaMagazin/NavigaMagazin/Views/Contentdetail/Index.cshtml
@using NavigaMagazin.Models.Entity
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<ContentTable>
@{
    ViewBag.Title = "İçerik";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<script>
    $('#myModal').on('shown.bs.modal', function () {
        $('#myInput').trigger('focus')
    })
    $('#myModal2').on('shown.bs.modal', function () {
        $('#myInput2').trigger('focus')
    })
    $('#myModal3').on('shown.bs.modal', function () {
        $('#myInput3').trigger('focus')
    })
    $('#myModal4').on('shown.bs.modal', function () {
        $('#myInput4').trigger('focus')
    })
</script>
<style>
    .modal-lg {
        width: 100% !important;
        max-width: 900px;
    }


</style>
<div class="page-header row no-gutters py-4">
    <div class="col-6 col-sm-6 text-center text-sm-left mb-0">
        <span class="text-uppercase page-subtitle">İçerik Yönetimi</span>
    </div>


    <div class="col-6 col-sm-6 text-center mb-0 ">
        <button class="btn btn-primary pull-right" data-toggle="modal" data-target="#exampleModal">İçerik Ara</button>
        <button class="btn btn-primary pull-right" data-toggle="modal" data-target="#exampleModal2">Yeni Kategori</button>
        <button class="btn btn-primary pull-right" data-toggle="modal" data-target="#exampleModal4">Kategoriler</button>
        <a href="@Url.Action("ContentAdd","Contentdetail")"><button class="btn btn-primary pull-right">Yeni İçerik</button></a>
    </div>
</div>
<hr />
<div class="row">
    @{int i = 1;}
    @foreach (var posts in Model)
    {
        <div class="col-lg-3 col-md-6 col-sm-12 mb-4">
            <div class="card card-small card-post card-post--1">
                <div class="card-post__image" style="background-image: url('@posts.postphoto');">
                    <a href="@Url.Action("DeleteContent", "Contentdetail" , new { id = posts.id })" onclick="return confirm('Bu İçeriği Silmek İstediğinize Emin Misiniz?')"><i class="material-icons badge badge-pill badge-secondary" style="color:white; padding:10px;">X</i></a>
                    <p class="card-post__category badge badge-pill badge-dark">@posts.CategoryTable.categoryname </p>
                    <div class="card-post__author d-flex">
                        <a href="#" class="card-post__author-avatar card-post__author-avatar--small" style="background-image: url('@posts.UserTable.userphoto')"></a>
                    </div>
                </div>
                <div class="card-body">
                    <h5 class="card-title">
                        <a class="text-fiord-blue" href="@Url.Action("UpdateContent", "Contentdetail" , new { id = posts.id })">@posts.posttitle</a>
                    </h5>
                    <span class="text-muted">@posts.releasetime.Value.ToString("dd.MM.yyyy")</span>
                </div>
            </div>
        </div>
    }


</div>
@*İçerik Ara*@
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form action="@Url.Action("SearchContent", "Contentdetail")" method="post" enctype="multipart/form-data" class="form-group">
                <div class="modal-header">
                    <h5 class="modal-title text-center" id="exampleModalLabel">Yeni Kategori</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <input type="text" name="searchkey" placeholder="İçerik Ara" required class="form-control" /><br />

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Kapat</button>
                    <input type="submit" class="btn btn-primary" value="Ara" />
                </div>
            </form>

        </div>
    </div>
</div>
@*Yeni Kategori*@
<div class="modal fade" id="exampleModal2" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">

            @{Html.RenderAction("CategoryAdd", "AdminPartial");}
        </div>
    </div>
</div>
@*Yeni İçerik*@
@*<div class="modal fade" id="exampleModal3" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-xl">
            >
            <div class="modal-content">

                @{Html.RenderAction("ContentAdd", "AdminPartial");}
            </div>
        </div>
    </div>*@

@*Kategoriler*@
<div class="modal fade" id="exampleModal4" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-center" id="exampleModalLabel">Kategoriler</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                @{Html.RenderAction("Categories", "AdminPartial");}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Kapat</button>

            </div>


        </div>
    </div>
</div>

<div class="row">
    
    <div class="col-lg-12 text-center">
        
    </div>
</div>

NavigaMagazin/NavigaMagazin/Views/Contentdetail/UpdateCat.cshtml
@model NavigaMagazin.Models.Entity.CategoryTable
@{
    ViewBag.Title = "UpdateCat";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<div class="page-header row no-gutters py-4">
    <div class="col-12 col-sm-12 text-center text-sm-left mb-0">
        <span class="text-uppercase page-subtitle">Kategori Güncelle</span>
    </div>
</div>
<hr />
@using (Html.BeginForm("UpdateCat", "Contentdetail", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="main-content-container container-fluid px-12">
        <div class="row">
            <div class="col-lg-12 col-md-12">
                <div class="card card-small mb-9">
                    <div class="card-body">

                        <label>Kategori Adı</label>
                        @Html.TextBoxFor(m => m.categoryname, new { @class = "form-control form-control-lg mb-3" })
                        @Html.DropDownListFor(m => m.menuid, (List<SelectListItem>)ViewBag.menus, new { @class = "ml-auto" })
                        <br /><br />
                        <button class="btn btn-sm btn-accent ml-auto">
                            <i class="material-icons">file_copy</i> Kaydet
                        </button>
                    </div>
                </div>
            </div>

        </div>
    </div>

}