NavigaMagazin/NavigaMagazin/Controllers/AdvertisementController.cs
using NavigaMagazin.Models.Entity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NavigaMagazin.Controllers
{
    public class AdvertisementController : BaseController
    {
        // GET: Advertisement
        navigaEntities db = new navigaEntities();
        public ActionResult Index()
        {
            ViewBag.ads = TempData["ads"];
            UserTable currentUser = (UserTable)Session["MySessionUser"];
            if (currentUser.UserRoleTable.rolename != "Admin")
            {
                return RedirectToAction("Index", "Admin");

            }
            else
            {
                var adlist = (from s in db.AdvertisingTables
                              where s.advertisingstart < DateTime.Now && s.advertisingend > DateTime.Now
                              orderby s.createtime descending
                              select s).ToList();
                return View(adlist);
            }
            
        }

        public ActionResult DeleteAd(int id)
        {
            UserTable currentUser = (UserTable)Session["MySessionUser"];
            var ad = db.AdvertisingTables.Find(id);
            var addlog = new ManualLog
            {
                logexp = "Reklam Silindi, Silinen Reklam : " + ad.advertisingname,
                whodidit = currentUser.username + " " + currentUser.usersurname,
                processingtime = DateTime.Now,
            };
            db.ManualLogs.Add(addlog);
            db.AdvertisingTables.Remove(ad);
            db.SaveChanges();
            return Redirect(ControllerContext.HttpContext.Request.UrlReferrer.ToString());
        }
        [HttpGet]
        public ActionResult UpdateAd(int id)
        {

            var ad = db.AdvertisingTables.Find(id);
            ViewBag.ads = TempData["ads"];
            return View("UpdateAd", ad);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult UpdateAd(AdvertisingTable p1, string advertisingformat)
        {
            UserTable currentUser = (UserTable)Session["MySessionUser"];
            var ad = db.AdvertisingTables.Find(p1.id);
            var stime = p1.advertisingstart;
            var etime = p1.advertisingend;
            if(p1.advertisingphoto != null)
            {
                var addphoto = Request.Files[0];
                var fileInfo = new FileInfo(addphoto.FileName);
                var pic = "AddPhoto" + DateTime.Now.Ticks + fileInfo.Extension;
                var filePath = "/Photos/AdPhotos/" + pic;
                var tempFilePath = Server.MapPath("~\\Photos\\AdPhotos\\" + pic);
                addphoto.SaveAs(tempFilePath);
                ad.advertisingphoto = filePath;
            }

            ad.advertisingname = p1.advertisingname;
            ad.advertisinglink = p1.advertisinglink;
            ad.advertisingstart = Convert.ToDateTime(stime);
            ad.advertisingend = Convert.ToDateTime(etime);
            ad.updatetime = DateTime.Now;
            ad.fixedad = p1.fixedad;
            ad.isaktif = p1.isaktif;

            if (advertisingformat == "260x230")
            {
                var control = (from s in db.AdvertisingTables
                               where s.advertising260x230 == "true" &&
                               s.advertisingstart < DateTime.Now && s.advertisingend > DateTime.Now
                               && s.fixedad != "true"
                               select s).Count();
                if (control >= 2 && p1.fixedad != "true")
                {
                    TempData["ads"] = string.Format("no");
                    return Redirect(ControllerContext.HttpContext.Request.UrlReferrer.ToString());
                }
                else
                {
                    ad.advertising260x230 = "true";
                    ad.advertising320x270 = null;
                    ad.advertising728x90 = null;
                    ad.advertising320x540 = null;
                    ad.advertising728x90banner = null;
                }
               
            }
            else if (advertisingformat == "320x270")
            {
                var control = (from s in db.AdvertisingTables
                               where s.advertising320x270 == "true" &&
                               s.advertisingstart < DateTime.Now && s.advertisingend > DateTime.Now
                               && s.fixedad != "true"
                               select s).Count();
                if (control >= 2 && p1.fixedad != "true")
                {
                    TempData["ads"] = string.Format("no");
                    return Redirect(ControllerContext.HttpContext.Request.UrlReferrer.ToString());
                }
                else
                {
                    ad.advertising260x230 = null;
                    ad.advertising320x270 = "true";
                    ad.advertising728x90 = null;
                    ad.advertising320x540 = null;
                    ad.advertising728x90banner = null;

                }
               
            }
            else if (advertisingformat == "728x90")
            {
                var control = (from s in db.AdvertisingTables
                               where s.advertising728x90 == "true" &&
                               s.advertisingstart < DateTime.Now && s.advertisingend > DateTime.Now
                               && s.fixedad != "true"
                               select s).Count();
                if (control >= 2 && p1.fixedad != "true")
                {
                    TempData["ads"] = string.Format("no");
                    return Redirect(ControllerContext.HttpContext.Request.UrlReferrer.ToString());
                }
                else
                {
                    ad.advertising260x230 = null;
                    ad.advertising320x270 = null;
                    ad.advertising728x90 = "true";
                    ad.advertising320x540 = null;
                    ad.advertising728x90banner = null;
                }
                
            }
            else if (advertisingformat == "728x90banner")
            {
                var control = (from s in db.AdvertisingTables
                               where s.advertising728x90banner == "true" &&
                               s.advertisingstart < DateTime.Now && s.advertisingend > DateTime.Now
                               && s.fixedad != "true"
                               select s).Count();
                if (control >= 2 && p1.fixedad != "true")
                {
                    TempData["ads"] = string.Format("no");
                    return Redirect(ControllerContext.HttpContext.Request.UrlReferrer.ToString());
                }
                else
                {
                    ad.advertising260x230 = null;
                    ad.advertising320x270 = null;
                    ad.advertising728x90 = null;
                    ad.advertising728x90banner = "true";
                    ad.advertising320x540 = null;
                }
                
            }
            else if (advertisingformat == "320x540")
            {
                var control = (from s in db.AdvertisingTables
                               where s.advertising320x540 == "true" &&
                               s.advertisingstart < DateTime.Now && s.advertisingend > DateTime.Now
                               && s.fixedad != "true"
                               select s).Count();
                if (control >= 2 && p1.fixedad != "true")
                {
                    TempData["ads"] = string.Format("no");
                    return Redirect(ControllerContext.HttpContext.Request.UrlReferrer.ToString());
                }
                else {
                    ad.advertising260x230 = null;
                    ad.advertising320x270 = null;
                    ad.advertising728x90 = null;
                    ad.advertising728x90banner = null;
                    ad.advertising320x540 = "true";
                }

            }

            var addlog = new ManualLog
            {
                logexp = "Reklam Güncellendi , Güncellenen Reklam : " + p1.advertisingname,
                whodidit = currentUser.username + " " + currentUser.usersurname,
                processingtime = DateTime.Now,
            };

            db.ManualLogs.Add(addlog);
            db.SaveChanges();
            return RedirectToAction("Index");

        }

        public ActionResult SearchAd(string searchkey)
        {
            var search = from x in db.AdvertisingTables
                         select x;
            if (!String.IsNullOrEmpty(searchkey))
            {
                search = search.Where(s => s.advertisingname.Contains(searchkey)          
                );
            }
            ViewBag.Words = searchkey;
            return View(search.ToList());
        }

    }
}

NavigaMagazin/NavigaMagazin/Views/Advertisement/Index.cshtml
@using NavigaMagazin.Models.Entity
@{
    ViewBag.Title = "Reklam Yönetimi";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<script>
    $('#myModal').on('shown.bs.modal', function () {
        $('#myInput').trigger('focus')
    })

</script>
@if (ViewBag.ads == "no")
{
    <div class="alert alert-danger text-center" role="alert">
        <h4 class="alert-heading">Başarısız !</h4><br />
        <p>Aynı formatta en fazla 2 aktif reklam eklenebilir ! </p>

    </div>
}

<div class="page-header row no-gutters py-4">
    <div class="col-6 col-sm-6 text-center text-sm-left mb-0">
        <span class="text-uppercase page-subtitle">Reklam Yönetimi</span>
    </div>
    <div class="col-6 col-sm-6 text-center mb-0 ">
        <button class="btn btn-primary pull-right" data-toggle="modal" data-target="#exampleModal2">Reklam Ara</button>
        <button class="btn btn-primary pull-right" data-toggle="modal" data-target="#exampleModal">Yeni Reklam</button>
    </div>
</div>
<div class="page-header row no-gutters py-4">
    <div class="col-12 col-sm-12 text-center text-sm-left mb-0">
        <span class="text-uppercase page-subtitle">Aktif Reklamlar</span>
    </div>
</div>
@if (Model.Count == 0)
{

    <div class="alert alert-danger text-center" role="alert">
        <h4 class="alert-heading">Aktif Reklam Yok !</h4><br />


    </div>
}
<div class="row">
    @foreach (var ads in Model)
    {
        <div class="col-lg-3 col-md-6 col-sm-12 mb-4">
            <div class="card card-small card-post card-post--1" style="border:#00ff21 solid 1px;">
                <div class="card-post__image" style="background-image: url('@ads.advertisingphoto');">
                    <a href="@Url.Action("DeleteAd", "Advertisement" , new { id = ads.id })" onclick="return confirm('Bu Reklamı Silmek İstediğinize Emin Misiniz?')">
                        <i class="material-icons badge badge-pill badge-secondary" style="color:white; padding:10px;">
                            <i class="fa fa-trash" aria-hidden="true"></i>
                        </i>
                    </a>
                    <p class="card-post__category badge badge-pill badge-dark">
                        <i class="fa fa-hand-pointer" aria-hidden="true"></i>
                        @ads.numberofclicks | <i class="fa fa-eye" aria-hidden="true"></i> @ads.numberofview
                    </p>
                </div>
                <div class="card-body">
                    <h5 class="card-title">
                        <a class="text-fiord-blue" href="@Url.Action("UpdateAd", "Advertisement" , new { id = ads.id })">@ads.advertisingname</a>
                    </h5>
                    <span class="text-muted">@ads.advertisingstart.ToString("dd.MM.yyyy") - @ads.advertisingend.ToString("dd.MM.yyyy") </span>
                    <br />
                    @if (ads.advertising260x230 == "true")
                    {<span class="text-muted"><b style="color:#ae3b3b">260x230</b></span>}
                    @if (ads.advertising320x270 == "true")
                    {<span class="text-muted"><b style="color:#ae3b3b">320x270</b></span>}
                    @if (ads.advertising320x540 == "true")
                    {<span class="text-muted"><b style="color:#ae3b3b">320x540</b></span>}

                    @if (ads.advertising728x90 == "true")
                    {<span class="text-muted"><b style="color:#ae3b3b">728x90</b></span>}
                    @if (ads.advertising728x90banner == "true")
                    {<span class="text-muted"><b style="color:#ae3b3b">728x90 Banner</b></span>}
                </div>
            </div>
        </div>
    }
</div>
<div class="page-header row no-gutters py-4">

    <div class="col-12 col-sm-12 text-center text-sm-left mb-0">
        <span class="text-uppercase page-subtitle">Gelecek Reklamlar</span>
    </div>
</div>
@{Html.RenderAction("FutureAd", "AdminPartial");}
<div class="page-header row no-gutters py-4">

    <div class="col-12 col-sm-12 text-center text-sm-left mb-0">
        <span class="text-uppercase page-subtitle">Biten Reklamlar</span>
    </div>
</div>
@{Html.RenderAction("ExpiredAd", "AdminPartial");}
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">

            @{Html.RenderAction("AdAdd", "AdminPartial");}
        </div>
    </div>
</div>
<div class="modal fade" id="exampleModal2" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form action="@Url.Action("SearchAd", "Advertisement")" method="post" enctype="multipart/form-data" class="form-group">
                <div class="modal-header">
                    <h5 class="modal-title text-center" id="exampleModalLabel">Reklam Ara</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <input type="text" name="searchkey" placeholder="Reklam Ara" required class="form-control" /><br />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Kapat</button>
                    <input type="submit" class="btn btn-primary" value="Ara" />
                </div>
            </form>

        </div>
    </div>
</div>

NavigaMagazin/NavigaMagazin/Views/Advertisement/SearchAd.cshtml
@using NavigaMagazin.Models.Entity
@{
    ViewBag.Title = "SearchAd";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<script>
    $('#myModal').on('shown.bs.modal', function () {
        $('#myInput').trigger('focus')
    })

</script>
<div class="page-header row no-gutters py-4">
    <div class="col-6 col-sm-6 text-center text-sm-left mb-0">
        <span class="text-uppercase page-subtitle">Aranan Reklam :  @ViewBag.Words</span>
    </div>
    <div class="col-6 col-sm-6 text-center mb-0 ">
        <button class="btn btn-primary pull-right" data-toggle="modal" data-target="#exampleModal2">Reklam Ara</button>

    </div>
</div>
<div class="row">
    @foreach (var searchad in Model)
    {
        <div class="col-lg-3 col-md-6 col-sm-12 mb-4">
            <div class="card card-small card-post card-post--1">
                <div class="card-post__image" style="background-image: url('@searchad.advertisingphoto');">
                    <a href="@Url.Action("DeleteAd", "Advertisement" , new { id = searchad.id })" onclick="return confirm('Bu Reklamı Silmek İstediğinize Emin Misiniz?')"><i class="material-icons badge badge-pill badge-secondary" style="color:white; padding:10px;">
    <i class="fa fa-trash" aria-hidden="true"></i>
</i></a>
                    <p class="card-post__category badge badge-pill badge-dark">
                        <i class="fa fa-hand-pointer" aria-hidden="true"></i>
                        @searchad.numberofclicks | <i class="fa fa-eye" aria-hidden="true"></i> @searchad.numberofview
                    </p>
                </div>
                <div class="card-body">
                    <h5 class="card-title">
                        <a class="text-fiord-blue" href="@Url.Action("UpdateAd", "Advertisement" , new { id = searchad.id })">@searchad.advertisingname</a>
                    </h5>
                    <span class="text-muted">@searchad.advertisingstart.ToString("dd.MM.yyyy") - @searchad.advertisingend.ToString("dd.MM.yyyy") </span>
                </div>
            </div>
        </div>
    }
</div>







<div class="modal fade" id="exampleModal2" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form action="@Url.Action("SearchAd", "Advertisement")" method="post" enctype="multipart/form-data" class="form-group">
                <div class="modal-header">
                    <h5 class="modal-title text-center" id="exampleModalLabel">Reklam Ara</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <input type="text" name="searchkey" placeholder="Reklam Ara" required class="form-control" /><br />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Kapat</button>
                    <input type="submit" class="btn btn-primary" value="Ara" />
                </div>
            </form>

        </div>
    </div>
</div>

NavigaMagazin/NavigaMagazin/Views/Advertisement/UpdateAd.cshtml
@model NavigaMagazin.Models.Entity.AdvertisingTable

@{
    ViewBag.Title = "Reklam Güncelle";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}


<div class="main-content-container container-fluid px-4">

    <div class="page-header row no-gutters py-4">
        <div class="col-12 col-sm-4 text-center text-sm-left mb-0">
            <span class="text-uppercase page-subtitle"></span>
            <h3 class="page-title">Reklam Güncelle</h3>
        </div>
    </div>
    @if (ViewBag.ads == "no")
    {
        <div class="alert alert-danger text-center" role="alert">
            <h4 class="alert-heading">Başarısız !</h4><br />
            <p>Aynı formatta en fazla 2 aktif reklam eklenebilir, Bu formatta 2 adet aktif reklam mevcut! </p>

        </div>
    }
    @using (Html.BeginForm("UpdateAd", "Advertisement", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="row">
            <div class="col-lg-9 col-md-12">
                <div class="card card-small mb-3">
                    <div class="card-body">

                        @Html.TextBoxFor(m => m.advertisingname, new { @class = "form-control form-control-lg mb-3", @maxlength = "65" })
                        @Html.TextBoxFor(m => m.advertisinglink, new { @class = "form-control form-control-lg mb-3", @maxlength = "170" })


                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-12">
                <div class='card card-small mb-3'>
                    <div class="card-header border-bottom">
                        <h6 class="m-0">Detaylar ve Fotoğraf</h6>
                    </div>
                    <div class='card-body p-0'>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item p-3">
                                <span class="d-flex mb-2">
                                    <i class="material-icons mr-1">flag</i>
                                    <strong class="mr-1">Durum </strong>
                                    @Html.DropDownListFor(m => m.isaktif, new List<SelectListItem>
               { new SelectListItem{Text="Aktif", Value="1"},
               new SelectListItem{Text="Pasif", Value="2"}}, new { @class = "ml-auto" })
                                </span>
                                <span class="d-flex mb-2">
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <img src="@Model.advertisingphoto" style="width:100%!important; padding:20px;" />
                                        </div>
                                        <div class="col-lg-6">
                                            <strong class="mr-1">Reklam Fotoğrafı<br /> </strong>
                                        </div>
                                        <div class="col-lg-6">
                                            <strong class="ml-1">
                                                <input type="file" name="advertisingphoto" />
                                            </strong>
                                        </div>
                                    </div>


                                </span>

                            </li>

                        </ul>
                    </div>
                </div>
                <div class='card card-small mb-3'>
                    <div class="card-header border-bottom">
                        <h6 class="m-0">Reklam Formatı</h6>
                    </div>
                    <div class='card-body p-0'>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item p-3">
                                <span class="d-flex mb-2">


                                    @if (Model.advertising260x230 == "true")
                                    {


                                        <select name="advertisingformat" class="form-control">
                                            <option value="260x230" selected>260x230</option>
                                            <option value="320x270">320x270</option>
                                            <option value="320x540">320x540</option>
                                            <option value="728x90">728x90</option>
                                            <option value="728x90banner">728x90 Banner</option>
                                        </select>
                                    }

                                    @if (Model.advertising320x270 == "true")
                                    {
                                        <select name="advertisingformat" class="form-control">
                                            <option value="260x230">260x230</option>
                                            <option value="320x270" selected>320x270</option>
                                            <option value="320x540">320x540</option>
                                            <option value="728x90">728x90</option>
                                            <option value="728x90banner">728x90 Banner</option>
                                        </select>
                                    }



                                    @if (Model.advertising320x540 == "true")
                                    {
                                        <select name="advertisingformat" class="form-control">
                                            <option value="260x230">260x230</option>
                                            <option value="320x270">320x270</option>
                                            <option value="320x540" selected>320x540</option>
                                            <option value="728x90">728x90</option>
                                            <option value="728x90banner">728x90 Banner</option>
                                        </select>
                                    }
                                    @if (Model.advertising728x90 == "true")
                                    {
                                        <select name="advertisingformat" class="form-control">
                                            <option value="260x230">260x230</option>
                                            <option value="320x270">320x270</option>
                                            <option value="320x540">320x540</option>
                                            <option value="728x90" selected>728x90</option>
                                            <option value="728x90banner">728x90 Banner</option>
                                        </select>
                                    }
                                    @if (Model.advertising728x90banner == "true")
                                    {
                                        <select name="advertisingformat" class="form-control">
                                            <option value="260x230">260x230</option>
                                            <option value="320x270">320x270</option>
                                            <option value="320x540">320x540</option>
                                            <option value="728x90">728x90</option>
                                            <option value="728x90banner" selected>728x90 Banner</option>
                                        </select>
                                    }
                                    <br /><br />

                                </span>
                                <strong class="mr-1">Sabit Reklam </strong>
                                @if (Model.fixedad == "true")
                                {
                                    <input type="checkbox" name="fixedad" value="true" checked>
                                }
                                else
                                {
                                    <input type="checkbox" name="fixedad" value="true">

                                }
                            </li>
                        </ul>
                    </div>
                </div>
                <div class='card card-small mb-3'>
                    <div class="card-header border-bottom">
                        <h6 class="m-0">Tarih</h6>
                    </div>
                    <div class='card-body p-0'>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item p-3">


                                <span class="d-flex mb-2">
                                    <i class="material-icons mr-1">calendar_today</i>
                                    <strong class="mr-1">Başlangıç Zamanı </strong>
                                    <input type="text" id="datepicker" name="advertisingstart" required="required" class="ml-auto" value="@Model.advertisingstart"><br />
                                </span>
                                <span class="d-flex mb-2">
                                    <i class="material-icons mr-1">calendar_today</i>
                                    <strong class="mr-1">Bitiş Zamanı </strong>
                                    <input type="text" id="datepicker2" name="advertisingend" required="required" class="ml-auto" value="@Model.advertisingend"><br />
                                </span>

                            </li>
                            <li class="list-group-item d-flex px-3">

                                <button class="btn btn-sm btn-accent ml-auto">
                                    <i class="material-icons">file_copy</i> Yayınla
                                </button>
                            </li>
                        </ul>
                    </div>
                </div>

            </div>
        </div>
    }
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.0/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js"></script>
    <script>
        $(function () {
            $("#datepicker").datepicker({
                dateFormat: 'yy-mm-dd'
            }).datepicker();
            ;
        });

        $(function () {
            $("#datepicker2").datepicker({
                dateFormat: 'yy-mm-dd'
            }).datepicker();
            ;
        });
    </script>
</div>